### ISSUE TITLE
Possible typo in requirements.txt

### ISSUE THREAD

**Issue by meowklaski** [p2p-today/p2p-project#129]
`custom-inherit` should be `custom_inherit` in requirements.txt, unless underscores are handled differently than I remember :)

**Comment by gappleto97** [comment]
Huh. It seems to have been working for me. I'll fix that right away though, in case that is not true on other systems.

**Comment by gappleto97** [comment]
287a9d6b7a16078f250ddaa88af03bd789a690d2 should fix that
