### ISSUE TITLE
Bug: pip install (python)

### ISSUE THREAD

**Issue by Kentoseth** [p2p-today/p2p-project#154]
Thought I would bring this issue up, as it is something I experienced when attempting to install this library.

Method to replicate:

OS - Debian/Ubuntu
Environment - attempt installing inside a `virtualenv`
Relevant versions - Python = 3.6.x ; pip = latest

`pip install py2p`

Results in failure due to missing/uninstalled packages/dependencies

Manual solution: Locate `requirements.txt` file (eg. on github) and install dependencies manually, then try `pip install py2p` which will work.

**Comment by LivInTheLookingGlass** [comment]
I'll try to take a look tomorrow evening. Thanks for letting me know.

**Comment by LivInTheLookingGlass** [comment]
Okay, I know what the problem is. I'll push a patch in the next little bit.

**Comment by LivInTheLookingGlass** [comment]
Okay, new version is pushed. You should be good now.
