### ISSUE TITLE
How to do NAT traversal ?

### ISSUE THREAD

**Issue by omkarjc27** [p2p-today/p2p-project#157]
In the python implementation of Mesh socket's documentation following is mentioned 
```
Using an outbound internet connection requires a little more work. 
First, ensure that you have a port forward set up 
(NAT busting is not in the scope of this project).
```
My question is that, Can I do NAT traversal using this library ? (in context of all nodes being under single or multiple levels of NATs)
If YES, how? 
And if NO what is the extra work to be done to do such a NAT traversal?

PS: Sorry if this sounds too trivial. I'm new to this library and also to p2p programming.

**Comment by LivInTheLookingGlass** [comment]
I have two main thoughts here.

First, you should almost certainly not use this library. While I do plan to redevelop it some day, this was done as my senior project for school, and its a mess. It isn't very stable, and it lacks some features that I would consider essential.

Second, NAT traversal can be done in a bunch of ways, but the easiest is probably through a UPnP library. I know there is at least one for Python, but I remember it having some issues building on Windows, so take that with a grain of salt.

**Comment by omkarjc27** [comment]
Thanks for the Reply.
