### ISSUE TITLE
Refactor code to have definitions in a more logical order

### ISSUE THREAD

**Issue by gappleto97** [p2p-today/p2p-project#65]
Things should not be used before they are defined

**Comment by pizzaisdavid** [comment]
Hey Gabe, I'd be willing to take a stab at this.

Looking at base.py I see the file is about 900 lines long. Is there any technical reason against breaking it into more manageable files? I was thinking of having a "base" folder and in there could be all the base classes.

```
base\
    brepr.py
    flags.py
    protocol.py
    ...
```

**Comment by gappleto97** [comment]
Not particularly, though I'd prefer to see the networking classes in one file. If you want to work on a fork/branch for this, I'd love to see what you come up with!
